CREATE DATABASE restaurante_db;

USE restaurante_db;

CREATE TABLE prato(
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome varchar(120) NOT NULL UNIQUE,
    preco DECIMAL(10, 2) NOT NULL,
    descricao  varchar(240) NOT NULL, /*virgula*/
);

CREATE TABLE pedidos(
    id INT AUTO_INCREMENT PRIMARY KEY,
    numero_mesa INT NOT NULL,
    nome_cliente varchar(120) NOT NULL,
    id_prato INT NOT NULL,
    FOREIGN KEY (id_prato) REFERENCES prato(id)
);

INSERT INTO prato (nome, preco, descricao) VALUES
('Spaghetti Carbonara', 28.50, 'Massa italiana com molho à base de ovos, queijo parmesão, pancetta e pimenta preta.'),
('Frango ao Curry', 32.00, 'Peito de frango cozido com molho cremoso de curry e especiarias.'),
('Lasanha Bolonhesa', 35.00, 'Camadas de massa, molho bolonhesa, queijo e molho bechamel.'),
('Salada Caesar', 22.00, 'Alface americana, croutons, molho Caesar e parmesão ralado.'),
('Risoto de Cogumelos', 38.50, 'Arroz arbóreo cremoso com cogumelos frescos e queijo parmesão.'),
('Bife à Parmegiana', 40.00, 'Bife empanado coberto com molho de tomate e queijo gratinado.'),
('Peixe Grelhado', 37.00, 'Filé de peixe fresco grelhado, servido com legumes ao vapor.'),
('Strogonoff de Carne', 34.50, 'Carne em tiras ao molho cremoso de creme de leite, molho de tomate e champignon.'),
('Bobó de Camarão', 45.00, 'Camarão cozido em creme de mandioca com leite de coco e azeite de dendê.'),
('Moqueca Baiana', 48.00, 'Peixe e camarão cozidos em leite de coco, azeite de dendê, pimentões e coentro.'),
('Pizza Margherita', 30.00, 'Pizza tradicional com molho de tomate, mussarela e manjericão.'),
('Hambúrguer Artesanal', 28.00, 'Hambúrguer caseiro com queijo cheddar, bacon e molho especial.'),
('Sushi Mix', 50.00, 'Seleção de sushi variados frescos.'),
('Caldo Verde', 18.00, 'Sopa tradicional portuguesa com couve, batata e linguiça.'),
('Quiche Lorraine', 25.00, 'Torta salgada com creme, bacon e queijo.'),
('Salada Caprese', 20.00, 'Tomate, mussarela de búfala, manjericão e azeite.'),
('Tacos Mexicanos', 33.00, 'Tacos recheados com carne, queijo, salsa e guacamole.'),
('Churrasco Misto', 55.00, 'Seleção de carnes grelhadas ao estilo brasileiro.'),
('Peito de Peru Assado', 42.00, 'Peito de peru assado com molho de laranja e mel.'),
('Panqueca de Carne', 27.00, 'Panqueca recheada com carne moída e molho de tomate.'),
('Filé Mignon ao Molho Madeira', 48.00, 'Filé mignon grelhado com molho madeira e champignon.'),
('Salada Grega', 22.00, 'Salada fresca com tomate, pepino, azeitona, queijo feta e azeite.'),
('Escondidinho de Carne Seca', 36.00, 'Purê de mandioca com carne seca desfiada e gratinado.'),
('Camarão na Moranga', 49.00, 'Camarão cremoso servido na abóbora moranga assada.'),
('Nhoque ao Molho Pesto', 30.00, 'Nhoque caseiro com molho pesto de manjericão e pinhões.'),
('Lombo Assado', 44.00, 'Lombo suíno assado com molho de maçã.'),
('Crepe de Queijo e Presunto', 26.00, 'Crepe recheado com queijo e presunto gratinado.'),
('Sopa de Abóbora', 20.00, 'Sopa cremosa feita com abóbora e especiarias.'),
('Feijoada Completa', 38.00, 'Tradicional feijoada brasileira com arroz, farofa e couve.'),
('Coxa de Frango Assada', 30.00, 'Coxa de frango temperada e assada lentamente.'),
('Sanduíche Club', 25.00, 'Sanduíche com frango, bacon, alface, tomate e maionese.'),
('Tilápia à Milanesa', 33.00, 'Filé de tilápia empanado e frito.'),
('Salada de Quinoa', 23.00, 'Salada nutritiva com quinoa, legumes e molho de limão.'),
('Canelone de Ricota', 34.00, 'Massa recheada com ricota e espinafre, coberta com molho branco.'),
('Bacalhau à Brás', 50.00, 'Bacalhau desfiado com batata palha, ovos e cebola.'),
('Carne de Panela', 37.00, 'Carne cozida lentamente com legumes.'),
('Esfiha de Carne', 22.00, 'Massa fina recheada com carne temperada.'),
('Frango Xadrez', 32.00, 'Frango salteado com legumes e molho oriental.'),
('Mousse de Chocolate', 18.00, 'Sobremesa cremosa de chocolate.'),
('Pavê de Morango', 20.00, 'Sobremesa em camadas com biscoito, creme e morangos.'),
('Torta de Limão', 22.00, 'Torta doce com creme de limão e merengue.'),
('Cheesecake', 25.00, 'Torta de queijo com calda de frutas vermelhas.'),
('Picanha Grelhada', 55.00, 'Picanha suculenta grelhada na brasa.'),
('Costela no Bafo', 52.00, 'Costela bovina cozida lentamente e desmanchando.'),
('Espaguete ao Alho e Óleo', 26.00, 'Massa simples com alho e azeite.'),
('Frango à Milanesa', 29.00, 'Peito de frango empanado e frito.'),
('Salada de Frutas', 18.00, 'Mix fresco de frutas da estação.'),
('Creme de Mandioquinha', 22.00, 'Sopa cremosa feita com mandioquinha.'),
('Espetinho de Carne', 35.00, 'Espetinhos variados de carne.'),
('Bobó Vegetariano', 40.00, 'Bobó feito com legumes e creme de mandioca.'),
('Moqueca de Peixe', 47.00, 'Peixe cozido com leite de coco e dendê.'),
('Polenta Cremosa', 25.00, 'Polenta feita com queijo e manteiga.'),
('Lasanha de Berinjela', 33.00, 'Lasanha feita com fatias de berinjela.'),
('Macarrão com Almôndegas', 34.00, 'Massa com almôndegas ao molho de tomate.'),
('Frango com Requeijão', 30.00, 'Frango desfiado com requeijão cremoso.'),
('Escondidinho de Frango', 35.00, 'Purê de mandioca com frango desfiado e gratinado.'),
('Salada de Atum', 28.00, 'Salada fresca com atum, ovos e legumes.'),
('Calabresa Acebolada', 27.00, 'Linguiça calabresa frita com cebola.'),
('Camarão Empanado', 45.00, 'Camarão empanado e frito.'),
('Frango ao Molho Barbecue', 32.00, 'Frango grelhado com molho barbecue.'),
('Arroz Carreteiro', 30.00, 'Arroz com carne seca e temperos.'),
('Peixe ao Forno', 38.00, 'Filé de peixe assado com legumes.'),
('Salmão Grelhado', 50.00, 'Filé de salmão grelhado com limão e ervas.'),
('Panqueca de Frango', 27.00, 'Panqueca recheada com frango e molho branco.'),
('Sopa de Legumes', 20.00, 'Sopa leve de legumes variados.'),
('Pão de Queijo', 15.00, 'Tradicional pão de queijo mineiro.'),
('Torta de Frango', 28.00, 'Torta salgada recheada com frango desfiado.'),
('Quibe Assado', 26.00, 'Quibe recheado assado no forno.'),
('Esfiha de Queijo', 22.00, 'Esfiha recheada com queijo.'),
('Salada Waldorf', 25.00, 'Salada com maçã, nozes, aipo e maionese.'),
('Omelete de Queijo', 20.00, 'Omelete simples com queijo.'),
('Arroz de Marisco', 45.00, 'Arroz com frutos do mar e temperos.'),
('Tilápia ao Molho de Alcaparras', 37.00, 'Filé de tilápia ao molho de alcaparras.'),
('Macarrão com Molho Alfredo', 32.00, 'Massa com molho cremoso de queijo.'),
('Caldinho de Feijão', 18.00, 'Caldo quente de feijão com temperos.'),
('Filé de Frango Grelhado', 30.00, 'Peito de frango grelhado temperado.'),
('Sushi Vegetariano', 40.00, 'Seleção de sushi sem peixe.'),
('Salada de Grão-de-Bico', 25.00, 'Salada com grão-de-bico, tomate e cebola.'),
('Torta de Maçã', 22.00, 'Torta doce com recheio de maçã.'),
('Bolo de Cenoura', 18.00, 'Bolo de cenoura com cobertura de chocolate.'),
('Crepe de Nutella', 25.00, 'Crepe doce recheado com Nutella.'),
('Milkshake de Morango', 20.00, 'Bebida gelada com morango e leite.'),
('Churrasco Vegetariano', 40.00, 'Variedade de legumes grelhados.'),
('Espaguete à Bolonhesa', 28.00, 'Massa com molho bolonhesa tradicional.'),
('Feijão Tropeiro', 35.00, 'Feijão com farinha, ovos e bacon.'),
('Camarão ao Alho e Óleo', 42.00, 'Camarões salteados no alho e azeite, servidos com arroz branco'),
('Penne ao Molho Alfredo', 29.50, 'Massa penne com molho cremoso de queijo e alho'),
('Sanduíche de Rosbife', 28.00, 'Pão francês recheado com rosbife, rúcula e mostarda'),
('Pasta Alla Norma', '35.50', 'Massa tradicional italiana com molho de tomate fresco, berinjela e manjericão'), /*aspas no valor*/
('Tortilla Espanhola', 24.00, 'Omelete com batatas e cebola caramelizada'),
('Fesenjan', 45.00, 'Um ensopado agridoce persa com nozes, romã e frango ou pato.'),
('Salada de Panela', 28.50, 'Prato mexicano feito com um tipo de cactus, tomate, cebola, coentro e queijo.'),
('Acarajé', 20.00, 'Prato típico da culinária baiana com bolinho de feijão fradinho frito e recheado.'),
('Empadão de Frango', 20, 'Uma torta salgada com massa crocante e recheio cremoso de frango desfiado.'),
('Huitlacoche', 30.20, 'Fungos de milho que são uma iguaria mexicana, usados em tacos e quesadillas.'),
('Moussaka', 48.90, 'Uma lasanha de beringela grega, com carne moída, batatas e molho bechamel.'),
('Bibimbap', 39.50, 'Prato coreano com arroz, vegetais salteados, carne, ovo e molho apimentado.'),
('Feijoada', 55.00, 'Uma feijoada vegana feita com feijão preto, cogumelos, e diversos vegetais.');

INSERT INTO pedidos (numero_mesa, nome_cliente) VALUES /*tirado a chave estrangeira*/
(15, 'Ana Silva', 23),
(3, 'Bruno Costa', 87),
(29, 'Carla Mendes', 5),
(12, 'Diego Santos', 33),
(7, 'Elisa Ramos', 11),
(24, 'Fabio Oliveira', 67),
(19, 'Gabriela Souza', 2),
(1, 'Hugo Lima', 44),
(22, 'Isabela Martins', 91),
(30, 'João Pedro', 76),
(9, 'Karla Almeida', 14),
(6, 'Lucas Fernandes', 51),
(13, 'Mariana Pereira', 9),
(28, 'Nicolas Rocha', 77),
(4, 'Olivia Castro', 39),
(25, 'Paulo Henrique', 59),
(2, 'Quésia Faria', 48),
(20, 'Rafael Teixeira', 17),
(18, 'Sofia Gomes', 64),
(5, 'Tiago Alves', 34),
(11, 'Ursula Pinto', 55),
(23, 'Vitor Barros', 1),
(8, 'Wanda Correia', 25),
(27, 'Xavier Duarte', 41),
(16, 'Yara Nunes', 19),
(10, 'Zeca Moura', 83),
(21, 'Amanda Castro', 38),
(30, 'Bruno Silva', 94),
(3, 'Cintia Lopes', 7),
(14, 'Daniel Reis', 36),
(1, 'Eduarda Lima', 49),
(7, 'Felipe Costa', 50),
(22, 'Giovana Rocha', 56),
(13, 'Henrique Almeida', 27),
(26, 'Ingrid Martins', 88),
(4, 'Joana Freitas', 80),
(9, 'Kevin Santos', 43),
(30, 'Larissa Fernandes', 99), /*prato que não existe*/
(17, 'Matheus Oliveira', 58),
(5, 'Natália Ramos', 31),
(12, 'Otávio Souza', 29),
(25, 'Patrícia Alves', 52),
(6, 'Renato Silva', 8),
(19, 'Sabrina Martins', 46),
(10, 'Thiago Pereira', 3),
(1, 'Ubirajara Costa', 53),
(23, 'Valéria Moreira', 68),
(7, 'Wallace Santos', 73),
(28, 'Xênia Ribeiro', 42),
(15, 'Yuri Santana', 79),
(3, 'Adriana Lima', 15),
(26, 'Bruno Gomes', 4),
(5, 'Camila Araújo', 20),
(22, 'Danilo Freitas', 78),
(12, 'Emanuel Costa', 62),
(9, 'Fabiana Silva', 47),
(18, 'Gustavo Moura', 30),
(1, 'Helena Nunes', 75),
(25, 'Igor Rocha', 10),
(7, 'Júlia Fernandes', 26),
(14, 'Karen Oliveira', 84),
(21, 'Leandro Lima', 24),
(8, 'Marcela Santos', 37),
(30, 'Natan Alves', 57),
(6, 'Olívia Pereira', 6),
(23, 'Pedro Henrique', 32),
(9, 'Raquel Costa', 54),
(13, 'Sérgio Martins', 35),
(2, 'Tatiana Souza', 13),
(27, 'Vinicius Ribeiro', 66),
(11, 'Aline Barros', 18),
(19, 'Breno Teixeira', 60),
(4, 'Cláudia Mendes', 40),
(15, 'Diego Almeida', 21),
(28, 'Elaine Freitas', 72),
(7, 'Fábio Santos', 22),
(23, 'Geovana Rocha', 28),
(3, 'Henrique Silva', 16),
(26, 'Isabela Costa', 85),
(12, 'João Almeida', 12),
(5, 'Karen Souza', 74),
(30, 'Lucas Pereira', 45),
(8, 'Mariana Oliveira', 63),
(20, 'Natasha Lima', 69),
(13, 'Otávio Martins', 90),
(6, 'Priscila Fernandes', 70),
(24, 'Rafael Santos', 76),
(2, 'Sabrina Almeida', 44),
(17, 'Tiago Costa', 81),
(9, 'Ursula Oliveira', 55),
(21, 'Valter Ramos', 34),
(10, 'Wesley Moreira', 50),
(27, 'Ximena Ribeiro', 39),
--(4, 'Yasmin Castro', 82), /*comentado a linha*/
(15, 'Zé Carlos Silva', 27),
(8, 'Ana Paula', 33),
(23, 'Bruno Henrique', 20),
(30, 'Melissa Stueber', 84);